var data = 
{
    "pbp": {
        "game": "701",
        "updatedTimestamp": "2013-4-8 23:46:37 AST",
        "period": [
            {
                "clk": "20:00",
                "num": "1",
                "play": [
                    {
                        "clk": "20:00",
                        "id": "1",
                        "ptsH": "0",
                        "ptsV": "0",
                        "tm": "H",
                        "desc": "Start of the 1st Half",
                        "playerFname": "",
                        "playerLname": "",
                        "eventId": "14",
                        "eventDesc": "Start Period",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "19:45",
                        "id": "2",
                        "ptsH": "0",
                        "ptsV": "0",
                        "tm": "H",
                        "desc": "Peyton Siva misses a layup shot.",
                        "playerFname": "Peyton",
                        "playerLname": "Siva",
                        "eventId": "4",
                        "eventDesc": "Field Goal Missed",
                        "distance": "0",
                        "xCoord": "0",
                        "yCoord": "0",
                        "teamId": "120"
                    },
                    {
                        "clk": "19:45",
                        "id": "3",
                        "ptsH": "0",
                        "ptsV": "0",
                        "tm": "V",
                        "desc": "Tim Hardaway Jr. with a defensive rebound.",
                        "playerFname": "Tim",
                        "playerLname": "Hardaway Jr.",
                        "eventId": "6",
                        "eventDesc": "Defensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "19:18",
                        "id": "4",
                        "ptsH": "0",
                        "ptsV": "2",
                        "tm": "V",
                        "desc": "Trey Burke makes a jump shot from 9 feet out.",
                        "playerFname": "Trey",
                        "playerLname": "Burke",
                        "eventId": "3",
                        "eventDesc": "Field Goal Made",
                        "distance": "9",
                        "xCoord": "-6.2",
                        "yCoord": "5.9",
                        "teamId": "75"
                    },
                    {
                        "clk": "18:57",
                        "id": "5",
                        "ptsH": "0",
                        "ptsV": "2",
                        "tm": "H",
                        "desc": "Russ Smith misses a jump shot from 9 feet out.",
                        "playerFname": "Russ",
                        "playerLname": "Smith",
                        "eventId": "4",
                        "eventDesc": "Field Goal Missed",
                        "distance": "9",
                        "xCoord": ".3",
                        "yCoord": "9.3",
                        "teamId": "120"
                    },
                    {
                        "clk": "18:57",
                        "id": "6",
                        "ptsH": "0",
                        "ptsV": "2",
                        "tm": "V",
                        "desc": "Trey Burke with a defensive rebound.",
                        "playerFname": "Trey",
                        "playerLname": "Burke",
                        "eventId": "6",
                        "eventDesc": "Defensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "18:49",
                        "id": "7",
                        "ptsH": "0",
                        "ptsV": "5",
                        "tm": "V",
                        "desc": "Trey Burke makes a 3-point jump shot from 27 feet out. Glenn Robinson III with the assist.",
                        "playerFname": "Trey",
                        "playerLname": "Burke",
                        "eventId": "3",
                        "eventDesc": "Field Goal Made",
                        "distance": "27",
                        "xCoord": "9.1",
                        "yCoord": "25.1",
                        "teamId": "75"
                    },
                    {
                        "clk": "18:30",
                        "id": "8",
                        "ptsH": "3",
                        "ptsV": "5",
                        "tm": "H",
                        "desc": "Wayne Blackshear makes a 3-point jump shot from 23 feet out. Gorgui Dieng with the assist.",
                        "playerFname": "Wayne",
                        "playerLname": "Blackshear",
                        "eventId": "3",
                        "eventDesc": "Field Goal Made",
                        "distance": "23",
                        "xCoord": "-14.5",
                        "yCoord": "18.4",
                        "teamId": "120"
                    },
                    {
                        "clk": "18:15",
                        "id": "9",
                        "ptsH": "3",
                        "ptsV": "5",
                        "tm": "V",
                        "desc": "Tim Hardaway Jr. misses a layup shot.",
                        "playerFname": "Tim",
                        "playerLname": "Hardaway Jr.",
                        "eventId": "4",
                        "eventDesc": "Field Goal Missed",
                        "distance": "0",
                        "xCoord": "0",
                        "yCoord": "0",
                        "teamId": "75"
                    },
                    {
                        "clk": "18:15",
                        "id": "10",
                        "ptsH": "3",
                        "ptsV": "5",
                        "tm": "H",
                        "desc": "Peyton Siva with a defensive rebound.",
                        "playerFname": "Peyton",
                        "playerLname": "Siva",
                        "eventId": "6",
                        "eventDesc": "Defensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "18:07",
                        "id": "11",
                        "ptsH": "3",
                        "ptsV": "5",
                        "tm": "V",
                        "desc": "Personal foul committed by Trey Burke.",
                        "playerFname": "Trey",
                        "playerLname": "Burke",
                        "eventId": "8",
                        "eventDesc": "Foul",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "18:01",
                        "id": "12",
                        "ptsH": "3",
                        "ptsV": "5",
                        "tm": "H",
                        "desc": "Russ Smith misses a jump shot from 17 feet out.",
                        "playerFname": "Russ",
                        "playerLname": "Smith",
                        "eventId": "4",
                        "eventDesc": "Field Goal Missed",
                        "distance": "17",
                        "xCoord": "17.3",
                        "yCoord": "1.3",
                        "teamId": "120"
                    },
                    {
                        "clk": "18:01",
                        "id": "13",
                        "ptsH": "3",
                        "ptsV": "5",
                        "tm": "V",
                        "desc": "Nik Stauskas with a defensive rebound.",
                        "playerFname": "Nik",
                        "playerLname": "Stauskas",
                        "eventId": "6",
                        "eventDesc": "Defensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "17:46",
                        "id": "14",
                        "ptsH": "3",
                        "ptsV": "5",
                        "tm": "V",
                        "desc": "Tim Hardaway Jr. misses a 3-point jump shot from 25 feet out.",
                        "playerFname": "Tim",
                        "playerLname": "Hardaway Jr.",
                        "eventId": "4",
                        "eventDesc": "Field Goal Missed",
                        "distance": "25",
                        "xCoord": "7.6",
                        "yCoord": "23.7",
                        "teamId": "75"
                    },
                    {
                        "clk": "17:46",
                        "id": "15",
                        "ptsH": "3",
                        "ptsV": "5",
                        "tm": "V",
                        "desc": "Glenn Robinson III with an offensive rebound.",
                        "playerFname": "Glenn",
                        "playerLname": "Robinson III",
                        "eventId": "5",
                        "eventDesc": "Offensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "17:22",
                        "id": "16",
                        "ptsH": "3",
                        "ptsV": "7",
                        "tm": "V",
                        "desc": "Trey Burke makes a layup shot.",
                        "playerFname": "Trey",
                        "playerLname": "Burke",
                        "eventId": "3",
                        "eventDesc": "Field Goal Made",
                        "distance": "0",
                        "xCoord": "0",
                        "yCoord": "0",
                        "teamId": "75"
                    },
                    {
                        "clk": "16:59",
                        "id": "17",
                        "ptsH": "3",
                        "ptsV": "7",
                        "tm": "H",
                        "desc": "Chane Behanan misses a layup shot.",
                        "playerFname": "Chane",
                        "playerLname": "Behanan",
                        "eventId": "4",
                        "eventDesc": "Field Goal Missed",
                        "distance": "0",
                        "xCoord": "0",
                        "yCoord": "0",
                        "teamId": "120"
                    },
                    {
                        "clk": "16:59",
                        "id": "18",
                        "ptsH": "3",
                        "ptsV": "7",
                        "tm": "H",
                        "desc": "Gorgui Dieng with an offensive rebound.",
                        "playerFname": "Gorgui",
                        "playerLname": "Dieng",
                        "eventId": "5",
                        "eventDesc": "Offensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "16:53",
                        "id": "19",
                        "ptsH": "5",
                        "ptsV": "7",
                        "tm": "H",
                        "desc": "Wayne Blackshear makes a layup shot. Gorgui Dieng with the assist.",
                        "playerFname": "Wayne",
                        "playerLname": "Blackshear",
                        "eventId": "3",
                        "eventDesc": "Field Goal Made",
                        "distance": "0",
                        "xCoord": "0",
                        "yCoord": "0",
                        "teamId": "120"
                    },
                    {
                        "clk": "16:21",
                        "id": "20",
                        "ptsH": "5",
                        "ptsV": "7",
                        "tm": "V",
                        "desc": "Trey Burke misses a layup shot.",
                        "playerFname": "Trey",
                        "playerLname": "Burke",
                        "eventId": "4",
                        "eventDesc": "Field Goal Missed",
                        "distance": "0",
                        "xCoord": "0",
                        "yCoord": "0",
                        "teamId": "75"
                    },
                    {
                        "clk": "16:21",
                        "id": "21",
                        "ptsH": "5",
                        "ptsV": "7",
                        "tm": "H",
                        "desc": "Gorgui Dieng with a defensive rebound.",
                        "playerFname": "Gorgui",
                        "playerLname": "Dieng",
                        "eventId": "6",
                        "eventDesc": "Defensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "16:14",
                        "id": "22",
                        "ptsH": "7",
                        "ptsV": "7",
                        "tm": "H",
                        "desc": "Russ Smith makes a layup shot. Peyton Siva with the assist.",
                        "playerFname": "Russ",
                        "playerLname": "Smith",
                        "eventId": "3",
                        "eventDesc": "Field Goal Made",
                        "distance": "0",
                        "xCoord": "0",
                        "yCoord": "0",
                        "teamId": "120"
                    },
                    {
                        "clk": "15:48",
                        "id": "23",
                        "ptsH": "7",
                        "ptsV": "7",
                        "tm": "V",
                        "desc": "Trey Burke with a lost ball turnover: Lost Ball",
                        "playerFname": "Trey",
                        "playerLname": "Burke",
                        "eventId": "7",
                        "eventDesc": "Turnover",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "15:37",
                        "id": "24",
                        "ptsH": "7",
                        "ptsV": "7",
                        "tm": "H",
                        "desc": "Russ Smith misses a layup shot.",
                        "playerFname": "Russ",
                        "playerLname": "Smith",
                        "eventId": "4",
                        "eventDesc": "Field Goal Missed",
                        "distance": "0",
                        "xCoord": "0",
                        "yCoord": "0",
                        "teamId": "120"
                    },
                    {
                        "clk": "15:37",
                        "id": "25",
                        "ptsH": "7",
                        "ptsV": "7",
                        "tm": "V",
                        "desc": "Nik Stauskas with a defensive rebound.",
                        "playerFname": "Nik",
                        "playerLname": "Stauskas",
                        "eventId": "6",
                        "eventDesc": "Defensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "15:34",
                        "id": "26",
                        "ptsH": "7",
                        "ptsV": "7",
                        "tm": "H",
                        "desc": "Shooting foul committed by Wayne Blackshear.",
                        "playerFname": "Wayne",
                        "playerLname": "Blackshear",
                        "eventId": "8",
                        "eventDesc": "Foul",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "15:34",
                        "id": "27",
                        "ptsH": "7",
                        "ptsV": "7",
                        "tm": "H",
                        "desc": "Official TV timeout.",
                        "playerFname": "",
                        "playerLname": "",
                        "eventId": "11",
                        "eventDesc": "Timeout",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "15:19",
                        "id": "28",
                        "ptsH": "7",
                        "ptsV": "7",
                        "tm": "V",
                        "desc": "Nik Stauskas misses a 3-point jump shot from 25 feet out.",
                        "playerFname": "Nik",
                        "playerLname": "Stauskas",
                        "eventId": "4",
                        "eventDesc": "Field Goal Missed",
                        "distance": "25",
                        "xCoord": "-10.6",
                        "yCoord": "22.4",
                        "teamId": "75"
                    },
                    {
                        "clk": "15:19",
                        "id": "29",
                        "ptsH": "7",
                        "ptsV": "7",
                        "tm": "V",
                        "desc": "Mitch McGary with an offensive rebound.",
                        "playerFname": "Mitch",
                        "playerLname": "McGary",
                        "eventId": "5",
                        "eventDesc": "Offensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "14:58",
                        "id": "30",
                        "ptsH": "7",
                        "ptsV": "10",
                        "tm": "V",
                        "desc": "Spike Albrecht makes a 3-point jump shot from 22 feet out. Nik Stauskas with the assist.",
                        "playerFname": "Spike",
                        "playerLname": "Albrecht",
                        "eventId": "3",
                        "eventDesc": "Field Goal Made",
                        "distance": "22",
                        "xCoord": "-21.7",
                        "yCoord": "3.3",
                        "teamId": "75"
                    },
                    {
                        "clk": "14:38",
                        "id": "31",
                        "ptsH": "9",
                        "ptsV": "10",
                        "tm": "H",
                        "desc": "Gorgui Dieng makes a jump shot from 19 feet out. Chane Behanan with the assist.",
                        "playerFname": "Gorgui",
                        "playerLname": "Dieng",
                        "eventId": "3",
                        "eventDesc": "Field Goal Made",
                        "distance": "19",
                        "xCoord": "4.5",
                        "yCoord": "18.3",
                        "teamId": "120"
                    },
                    {
                        "clk": "14:21",
                        "id": "32",
                        "ptsH": "9",
                        "ptsV": "12",
                        "tm": "V",
                        "desc": "Glenn Robinson III makes a layup shot. Tim Hardaway Jr. with the assist.",
                        "playerFname": "Glenn",
                        "playerLname": "Robinson III",
                        "eventId": "3",
                        "eventDesc": "Field Goal Made",
                        "distance": "0",
                        "xCoord": "0",
                        "yCoord": "0",
                        "teamId": "75"
                    },
                    {
                        "clk": "13:59",
                        "id": "33",
                        "ptsH": "11",
                        "ptsV": "12",
                        "tm": "H",
                        "desc": "Chane Behanan makes a dunk shot. Russ Smith with the assist.",
                        "playerFname": "Chane",
                        "playerLname": "Behanan",
                        "eventId": "3",
                        "eventDesc": "Field Goal Made",
                        "distance": "0",
                        "xCoord": "0",
                        "yCoord": "0",
                        "teamId": "120"
                    },
                    {
                        "clk": "13:34",
                        "id": "34",
                        "ptsH": "11",
                        "ptsV": "14",
                        "tm": "V",
                        "desc": "Mitch McGary makes a jump shot from 13 feet out. Tim Hardaway Jr. with the assist.",
                        "playerFname": "Mitch",
                        "playerLname": "McGary",
                        "eventId": "3",
                        "eventDesc": "Field Goal Made",
                        "distance": "13",
                        "xCoord": ".9",
                        "yCoord": "12.8",
                        "teamId": "75"
                    },
                    {
                        "clk": "13:12",
                        "id": "35",
                        "ptsH": "11",
                        "ptsV": "14",
                        "tm": "H",
                        "desc": "Russ Smith misses a 3-point jump shot from 23 feet out.",
                        "playerFname": "Russ",
                        "playerLname": "Smith",
                        "eventId": "4",
                        "eventDesc": "Field Goal Missed",
                        "distance": "23",
                        "xCoord": "-12.5",
                        "yCoord": "19.8",
                        "teamId": "120"
                    },
                    {
                        "clk": "13:12",
                        "id": "36",
                        "ptsH": "11",
                        "ptsV": "14",
                        "tm": "V",
                        "desc": "Tim Hardaway Jr. with a defensive rebound.",
                        "playerFname": "Tim",
                        "playerLname": "Hardaway Jr.",
                        "eventId": "6",
                        "eventDesc": "Defensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "13:06",
                        "id": "37",
                        "ptsH": "11",
                        "ptsV": "17",
                        "tm": "V",
                        "desc": "Spike Albrecht makes a 3-point jump shot from 26 feet out. Tim Hardaway Jr. with the assist.",
                        "playerFname": "Spike",
                        "playerLname": "Albrecht",
                        "eventId": "3",
                        "eventDesc": "Field Goal Made",
                        "distance": "26",
                        "xCoord": "18.1",
                        "yCoord": "18.1",
                        "teamId": "75"
                    },
                    {
                        "clk": "12:49",
                        "id": "38",
                        "ptsH": "11",
                        "ptsV": "17",
                        "tm": "V",
                        "desc": "Shooting foul committed by Glenn Robinson III.",
                        "playerFname": "Glenn",
                        "playerLname": "Robinson III",
                        "eventId": "8",
                        "eventDesc": "Foul",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "12:49",
                        "id": "39",
                        "ptsH": "12",
                        "ptsV": "17",
                        "tm": "H",
                        "desc": "Peyton Siva makes free throw 1 of 2.",
                        "playerFname": "Peyton",
                        "playerLname": "Siva",
                        "eventId": "1",
                        "eventDesc": "Free Throw Made",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "12:49",
                        "id": "40",
                        "ptsH": "13",
                        "ptsV": "17",
                        "tm": "H",
                        "desc": "Peyton Siva makes free throw 2 of 2.",
                        "playerFname": "Peyton",
                        "playerLname": "Siva",
                        "eventId": "1",
                        "eventDesc": "Free Throw Made",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "12:19",
                        "id": "41",
                        "ptsH": "13",
                        "ptsV": "17",
                        "tm": "V",
                        "desc": "Tim Hardaway Jr. misses a 3-point jump shot from 25 feet out.",
                        "playerFname": "Tim",
                        "playerLname": "Hardaway Jr.",
                        "eventId": "4",
                        "eventDesc": "Field Goal Missed",
                        "distance": "25",
                        "xCoord": "19.8",
                        "yCoord": "14.5",
                        "teamId": "75"
                    },
                    {
                        "clk": "12:19",
                        "id": "42",
                        "ptsH": "13",
                        "ptsV": "17",
                        "tm": "V",
                        "desc": "Jon Horford with an offensive rebound.",
                        "playerFname": "Jon",
                        "playerLname": "Horford",
                        "eventId": "5",
                        "eventDesc": "Offensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "12:16",
                        "id": "43",
                        "ptsH": "13",
                        "ptsV": "17",
                        "tm": "H",
                        "desc": "Personal foul committed by Gorgui Dieng.",
                        "playerFname": "Gorgui",
                        "playerLname": "Dieng",
                        "eventId": "8",
                        "eventDesc": "Foul",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "12:04",
                        "id": "44",
                        "ptsH": "13",
                        "ptsV": "20",
                        "tm": "V",
                        "desc": "Spike Albrecht makes a 3-point jump shot from 26 feet out. Trey Burke with the assist.",
                        "playerFname": "Spike",
                        "playerLname": "Albrecht",
                        "eventId": "3",
                        "eventDesc": "Field Goal Made",
                        "distance": "26",
                        "xCoord": "6.2",
                        "yCoord": "24.9",
                        "teamId": "75"
                    },
                    {
                        "clk": "11:46",
                        "id": "45",
                        "ptsH": "15",
                        "ptsV": "20",
                        "tm": "H",
                        "desc": "Peyton Siva makes a layup shot.",
                        "playerFname": "Peyton",
                        "playerLname": "Siva",
                        "eventId": "3",
                        "eventDesc": "Field Goal Made",
                        "distance": "0",
                        "xCoord": "0",
                        "yCoord": "0",
                        "teamId": "120"
                    },
                    {
                        "clk": "11:41",
                        "id": "46",
                        "ptsH": "15",
                        "ptsV": "20",
                        "tm": "H",
                        "desc": "Official TV timeout.",
                        "playerFname": "",
                        "playerLname": "",
                        "eventId": "11",
                        "eventDesc": "Timeout",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "11:18",
                        "id": "47",
                        "ptsH": "15",
                        "ptsV": "20",
                        "tm": "V",
                        "desc": "Mitch McGary misses a jump shot from 15 feet out.",
                        "playerFname": "Mitch",
                        "playerLname": "McGary",
                        "eventId": "4",
                        "eventDesc": "Field Goal Missed",
                        "distance": "15",
                        "xCoord": "8.2",
                        "yCoord": "12.7",
                        "teamId": "75"
                    },
                    {
                        "clk": "11:18",
                        "id": "48",
                        "ptsH": "15",
                        "ptsV": "20",
                        "tm": "H",
                        "desc": "Luke Hancock with a defensive rebound.",
                        "playerFname": "Luke",
                        "playerLname": "Hancock",
                        "eventId": "6",
                        "eventDesc": "Defensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "11:09",
                        "id": "49",
                        "ptsH": "15",
                        "ptsV": "20",
                        "tm": "V",
                        "desc": "Shooting foul committed by Trey Burke.",
                        "playerFname": "Trey",
                        "playerLname": "Burke",
                        "eventId": "8",
                        "eventDesc": "Foul",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "11:09",
                        "id": "50",
                        "ptsH": "15",
                        "ptsV": "20",
                        "tm": "H",
                        "desc": "Luke Hancock misses free throw 1 of 3.",
                        "playerFname": "Luke",
                        "playerLname": "Hancock",
                        "eventId": "2",
                        "eventDesc": "Free Throw Missed",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "11:09",
                        "id": "51",
                        "ptsH": "15",
                        "ptsV": "20",
                        "tm": "H",
                        "desc": "Lou with an offensive rebound.",
                        "playerFname": "",
                        "playerLname": "",
                        "eventId": "5",
                        "eventDesc": "Offensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "11:09",
                        "id": "52",
                        "ptsH": "16",
                        "ptsV": "20",
                        "tm": "H",
                        "desc": "Luke Hancock makes free throw 2 of 3.",
                        "playerFname": "Luke",
                        "playerLname": "Hancock",
                        "eventId": "1",
                        "eventDesc": "Free Throw Made",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "11:09",
                        "id": "53",
                        "ptsH": "17",
                        "ptsV": "20",
                        "tm": "H",
                        "desc": "Luke Hancock makes free throw 3 of 3.",
                        "playerFname": "Luke",
                        "playerLname": "Hancock",
                        "eventId": "1",
                        "eventDesc": "Free Throw Made",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "10:54",
                        "id": "54",
                        "ptsH": "17",
                        "ptsV": "20",
                        "tm": "V",
                        "desc": "Tim Hardaway Jr. with a lost ball turnover: Lost Ball",
                        "playerFname": "Tim",
                        "playerLname": "Hardaway Jr.",
                        "eventId": "7",
                        "eventDesc": "Turnover",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "10:33",
                        "id": "55",
                        "ptsH": "17",
                        "ptsV": "20",
                        "tm": "H",
                        "desc": "Russ Smith with a bad pass turnover: Bad Pass",
                        "playerFname": "Russ",
                        "playerLname": "Smith",
                        "eventId": "7",
                        "eventDesc": "Turnover",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "10:10",
                        "id": "56",
                        "ptsH": "17",
                        "ptsV": "20",
                        "tm": "V",
                        "desc": "Tim Hardaway Jr. with a lost ball turnover: Lost Ball",
                        "playerFname": "Tim",
                        "playerLname": "Hardaway Jr.",
                        "eventId": "7",
                        "eventDesc": "Turnover",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "10:04",
                        "id": "57",
                        "ptsH": "17",
                        "ptsV": "20",
                        "tm": "H",
                        "desc": "Russ Smith misses a layup shot.",
                        "playerFname": "Russ",
                        "playerLname": "Smith",
                        "eventId": "4",
                        "eventDesc": "Field Goal Missed",
                        "distance": "0",
                        "xCoord": "0",
                        "yCoord": "0",
                        "teamId": "120"
                    },
                    {
                        "clk": "10:04",
                        "id": "58",
                        "ptsH": "17",
                        "ptsV": "20",
                        "tm": "H",
                        "desc": "Stephan Van Treese with an offensive rebound.",
                        "playerFname": "Stephan",
                        "playerLname": "Van Treese",
                        "eventId": "5",
                        "eventDesc": "Offensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "9:41",
                        "id": "59",
                        "ptsH": "17",
                        "ptsV": "20",
                        "tm": "H",
                        "desc": "Gorgui Dieng with a double dribble turnover: Double Dribble",
                        "playerFname": "Gorgui",
                        "playerLname": "Dieng",
                        "eventId": "7",
                        "eventDesc": "Turnover",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "9:29",
                        "id": "60",
                        "ptsH": "17",
                        "ptsV": "22",
                        "tm": "V",
                        "desc": "Spike Albrecht makes a jump shot from 9 feet out.",
                        "playerFname": "Spike",
                        "playerLname": "Albrecht",
                        "eventId": "3",
                        "eventDesc": "Field Goal Made",
                        "distance": "9",
                        "xCoord": "-1.8",
                        "yCoord": "8.4",
                        "teamId": "75"
                    },
                    {
                        "clk": "9:07",
                        "id": "61",
                        "ptsH": "17",
                        "ptsV": "22",
                        "tm": "H",
                        "desc": "Russ Smith misses a layup shot.",
                        "playerFname": "Russ",
                        "playerLname": "Smith",
                        "eventId": "4",
                        "eventDesc": "Field Goal Missed",
                        "distance": "0",
                        "xCoord": "0",
                        "yCoord": "0",
                        "teamId": "120"
                    },
                    {
                        "clk": "9:07",
                        "id": "62",
                        "ptsH": "17",
                        "ptsV": "22",
                        "tm": "V",
                        "desc": "Spike Albrecht with a defensive rebound.",
                        "playerFname": "Spike",
                        "playerLname": "Albrecht",
                        "eventId": "6",
                        "eventDesc": "Defensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "9:02",
                        "id": "63",
                        "ptsH": "17",
                        "ptsV": "25",
                        "tm": "V",
                        "desc": "Nik Stauskas makes a 3-point jump shot from 23 feet out. Mitch McGary with the assist.",
                        "playerFname": "Nik",
                        "playerLname": "Stauskas",
                        "eventId": "3",
                        "eventDesc": "Field Goal Made",
                        "distance": "23",
                        "xCoord": "23",
                        "yCoord": "2",
                        "teamId": "75"
                    },
                    {
                        "clk": "8:31",
                        "id": "64",
                        "ptsH": "17",
                        "ptsV": "25",
                        "tm": "H",
                        "desc": "Russ Smith misses a layup shot.",
                        "playerFname": "Russ",
                        "playerLname": "Smith",
                        "eventId": "4",
                        "eventDesc": "Field Goal Missed",
                        "distance": "0",
                        "xCoord": "0",
                        "yCoord": "0",
                        "teamId": "120"
                    },
                    {
                        "clk": "8:31",
                        "id": "65",
                        "ptsH": "17",
                        "ptsV": "25",
                        "tm": "V",
                        "desc": "Caris LeVert with a defensive rebound.",
                        "playerFname": "Caris",
                        "playerLname": "LeVert",
                        "eventId": "6",
                        "eventDesc": "Defensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "8:13",
                        "id": "66",
                        "ptsH": "17",
                        "ptsV": "25",
                        "tm": "H",
                        "desc": "Shooting foul committed by Tim Henderson.",
                        "playerFname": "Tim",
                        "playerLname": "Henderson",
                        "eventId": "8",
                        "eventDesc": "Foul",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "8:13",
                        "id": "67",
                        "ptsH": "17",
                        "ptsV": "25",
                        "tm": "V",
                        "desc": "Spike Albrecht misses free throw 1 of 2.",
                        "playerFname": "Spike",
                        "playerLname": "Albrecht",
                        "eventId": "2",
                        "eventDesc": "Free Throw Missed",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "8:13",
                        "id": "68",
                        "ptsH": "17",
                        "ptsV": "25",
                        "tm": "V",
                        "desc": "Mich with an offensive rebound.",
                        "playerFname": "",
                        "playerLname": "",
                        "eventId": "5",
                        "eventDesc": "Offensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "8:13",
                        "id": "69",
                        "ptsH": "17",
                        "ptsV": "26",
                        "tm": "V",
                        "desc": "Spike Albrecht makes free throw 2 of 2.",
                        "playerFname": "Spike",
                        "playerLname": "Albrecht",
                        "eventId": "1",
                        "eventDesc": "Free Throw Made",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "7:56",
                        "id": "70",
                        "ptsH": "19",
                        "ptsV": "26",
                        "tm": "H",
                        "desc": "Chane Behanan makes a dunk shot. Gorgui Dieng with the assist.",
                        "playerFname": "Chane",
                        "playerLname": "Behanan",
                        "eventId": "3",
                        "eventDesc": "Field Goal Made",
                        "distance": "0",
                        "xCoord": "0",
                        "yCoord": "0",
                        "teamId": "120"
                    },
                    {
                        "clk": "7:45",
                        "id": "71",
                        "ptsH": "19",
                        "ptsV": "26",
                        "tm": "H",
                        "desc": "Personal foul committed by Russ Smith.",
                        "playerFname": "Russ",
                        "playerLname": "Smith",
                        "eventId": "8",
                        "eventDesc": "Foul",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "7:45",
                        "id": "72",
                        "ptsH": "19",
                        "ptsV": "26",
                        "tm": "H",
                        "desc": "Official TV timeout.",
                        "playerFname": "",
                        "playerLname": "",
                        "eventId": "11",
                        "eventDesc": "Timeout",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "7:18",
                        "id": "73",
                        "ptsH": "19",
                        "ptsV": "28",
                        "tm": "V",
                        "desc": "Mitch McGary makes a jump shot from 15 feet out. Nik Stauskas with the assist.",
                        "playerFname": "Mitch",
                        "playerLname": "McGary",
                        "eventId": "3",
                        "eventDesc": "Field Goal Made",
                        "distance": "15",
                        "xCoord": "13.2",
                        "yCoord": "6.7",
                        "teamId": "75"
                    },
                    {
                        "clk": "7:04",
                        "id": "74",
                        "ptsH": "19",
                        "ptsV": "28",
                        "tm": "H",
                        "desc": "Peyton Siva with a lost ball turnover: Lost Ball",
                        "playerFname": "Peyton",
                        "playerLname": "Siva",
                        "eventId": "7",
                        "eventDesc": "Turnover",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "6:54",
                        "id": "75",
                        "ptsH": "19",
                        "ptsV": "28",
                        "tm": "V",
                        "desc": "Jordan Morgan misses a layup shot.",
                        "playerFname": "Jordan",
                        "playerLname": "Morgan",
                        "eventId": "4",
                        "eventDesc": "Field Goal Missed",
                        "distance": "0",
                        "xCoord": "0",
                        "yCoord": "0",
                        "teamId": "75"
                    },
                    {
                        "clk": "6:54",
                        "id": "76",
                        "ptsH": "19",
                        "ptsV": "28",
                        "tm": "V",
                        "desc": "Caris LeVert with an offensive rebound.",
                        "playerFname": "Caris",
                        "playerLname": "LeVert",
                        "eventId": "5",
                        "eventDesc": "Offensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "6:39",
                        "id": "77",
                        "ptsH": "19",
                        "ptsV": "28",
                        "tm": "V",
                        "desc": "Mitch McGary misses a layup shot.",
                        "playerFname": "Mitch",
                        "playerLname": "McGary",
                        "eventId": "4",
                        "eventDesc": "Field Goal Missed",
                        "distance": "0",
                        "xCoord": "0",
                        "yCoord": "0",
                        "teamId": "75"
                    },
                    {
                        "clk": "6:39",
                        "id": "78",
                        "ptsH": "19",
                        "ptsV": "28",
                        "tm": "V",
                        "desc": "Jordan Morgan with an offensive rebound.",
                        "playerFname": "Jordan",
                        "playerLname": "Morgan",
                        "eventId": "5",
                        "eventDesc": "Offensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "6:34",
                        "id": "79",
                        "ptsH": "19",
                        "ptsV": "28",
                        "tm": "V",
                        "desc": "Jordan Morgan misses a layup shot.",
                        "playerFname": "Jordan",
                        "playerLname": "Morgan",
                        "eventId": "4",
                        "eventDesc": "Field Goal Missed",
                        "distance": "0",
                        "xCoord": "0",
                        "yCoord": "0",
                        "teamId": "75"
                    },
                    {
                        "clk": "6:34",
                        "id": "80",
                        "ptsH": "19",
                        "ptsV": "28",
                        "tm": "H",
                        "desc": "Peyton Siva with a defensive rebound.",
                        "playerFname": "Peyton",
                        "playerLname": "Siva",
                        "eventId": "6",
                        "eventDesc": "Defensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "6:29",
                        "id": "81",
                        "ptsH": "19",
                        "ptsV": "28",
                        "tm": "V",
                        "desc": "Shooting foul committed by Nik Stauskas.",
                        "playerFname": "Nik",
                        "playerLname": "Stauskas",
                        "eventId": "8",
                        "eventDesc": "Foul",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "6:29",
                        "id": "82",
                        "ptsH": "20",
                        "ptsV": "28",
                        "tm": "H",
                        "desc": "Russ Smith makes free throw 1 of 2.",
                        "playerFname": "Russ",
                        "playerLname": "Smith",
                        "eventId": "1",
                        "eventDesc": "Free Throw Made",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "6:29",
                        "id": "83",
                        "ptsH": "21",
                        "ptsV": "28",
                        "tm": "H",
                        "desc": "Russ Smith makes free throw 2 of 2.",
                        "playerFname": "Russ",
                        "playerLname": "Smith",
                        "eventId": "1",
                        "eventDesc": "Free Throw Made",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "6:06",
                        "id": "84",
                        "ptsH": "21",
                        "ptsV": "28",
                        "tm": "V",
                        "desc": "Glenn Robinson III misses a 3-point jump shot from 23 feet out.",
                        "playerFname": "Glenn",
                        "playerLname": "Robinson III",
                        "eventId": "4",
                        "eventDesc": "Field Goal Missed",
                        "distance": "23",
                        "xCoord": "23",
                        "yCoord": "3",
                        "teamId": "75"
                    },
                    {
                        "clk": "6:06",
                        "id": "85",
                        "ptsH": "21",
                        "ptsV": "28",
                        "tm": "V",
                        "desc": "Mitch McGary with an offensive rebound.",
                        "playerFname": "Mitch",
                        "playerLname": "McGary",
                        "eventId": "5",
                        "eventDesc": "Offensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "5:58",
                        "id": "86",
                        "ptsH": "21",
                        "ptsV": "31",
                        "tm": "V",
                        "desc": "Spike Albrecht makes a 3-point jump shot from 26 feet out.",
                        "playerFname": "Spike",
                        "playerLname": "Albrecht",
                        "eventId": "3",
                        "eventDesc": "Field Goal Made",
                        "distance": "26",
                        "xCoord": "-.4",
                        "yCoord": "25.8",
                        "teamId": "75"
                    },
                    {
                        "clk": "5:41",
                        "id": "87",
                        "ptsH": "21",
                        "ptsV": "31",
                        "tm": "H",
                        "desc": "Russ Smith misses a layup shot.",
                        "playerFname": "Russ",
                        "playerLname": "Smith",
                        "eventId": "4",
                        "eventDesc": "Field Goal Missed",
                        "distance": "0",
                        "xCoord": "0",
                        "yCoord": "0",
                        "teamId": "120"
                    },
                    {
                        "clk": "5:41",
                        "id": "88",
                        "ptsH": "21",
                        "ptsV": "31",
                        "tm": "V",
                        "desc": "Mitch McGary with a defensive rebound.",
                        "playerFname": "Mitch",
                        "playerLname": "McGary",
                        "eventId": "6",
                        "eventDesc": "Defensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "5:34",
                        "id": "89",
                        "ptsH": "21",
                        "ptsV": "31",
                        "tm": "H",
                        "desc": "Personal foul committed by Luke Hancock.",
                        "playerFname": "Luke",
                        "playerLname": "Hancock",
                        "eventId": "8",
                        "eventDesc": "Foul",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "5:21",
                        "id": "90",
                        "ptsH": "21",
                        "ptsV": "31",
                        "tm": "V",
                        "desc": "Spike Albrecht misses a layup shot.",
                        "playerFname": "Spike",
                        "playerLname": "Albrecht",
                        "eventId": "4",
                        "eventDesc": "Field Goal Missed",
                        "distance": "0",
                        "xCoord": "0",
                        "yCoord": "0",
                        "teamId": "75"
                    },
                    {
                        "clk": "5:21",
                        "id": "91",
                        "ptsH": "21",
                        "ptsV": "31",
                        "tm": "H",
                        "desc": "Chane Behanan with a defensive rebound.",
                        "playerFname": "Chane",
                        "playerLname": "Behanan",
                        "eventId": "6",
                        "eventDesc": "Defensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "5:19",
                        "id": "92",
                        "ptsH": "21",
                        "ptsV": "31",
                        "tm": "V",
                        "desc": "Personal foul committed by Mitch McGary.",
                        "playerFname": "Mitch",
                        "playerLname": "McGary",
                        "eventId": "8",
                        "eventDesc": "Foul",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "4:45",
                        "id": "93",
                        "ptsH": "21",
                        "ptsV": "31",
                        "tm": "H",
                        "desc": "Chane Behanan with a lost ball turnover: Lost Ball",
                        "playerFname": "Chane",
                        "playerLname": "Behanan",
                        "eventId": "7",
                        "eventDesc": "Turnover",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "4:43",
                        "id": "94",
                        "ptsH": "21",
                        "ptsV": "31",
                        "tm": "V",
                        "desc": "Mitch McGary with a traveling turnover: Traveling",
                        "playerFname": "Mitch",
                        "playerLname": "McGary",
                        "eventId": "7",
                        "eventDesc": "Turnover",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "4:36",
                        "id": "95",
                        "ptsH": "21",
                        "ptsV": "31",
                        "tm": "H",
                        "desc": "Gorgui Dieng misses a jump shot from 8 feet out.",
                        "playerFname": "Gorgui",
                        "playerLname": "Dieng",
                        "eventId": "4",
                        "eventDesc": "Field Goal Missed",
                        "distance": "8",
                        "xCoord": "-.1",
                        "yCoord": "7.6",
                        "teamId": "120"
                    },
                    {
                        "clk": "4:36",
                        "id": "96",
                        "ptsH": "21",
                        "ptsV": "31",
                        "tm": "V",
                        "desc": "Glenn Robinson III with a defensive rebound.",
                        "playerFname": "Glenn",
                        "playerLname": "Robinson III",
                        "eventId": "6",
                        "eventDesc": "Defensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "4:24",
                        "id": "97",
                        "ptsH": "21",
                        "ptsV": "31",
                        "tm": "H",
                        "desc": "Personal foul committed by Russ Smith.",
                        "playerFname": "Russ",
                        "playerLname": "Smith",
                        "eventId": "8",
                        "eventDesc": "Foul",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "4:08",
                        "id": "98",
                        "ptsH": "21",
                        "ptsV": "31",
                        "tm": "V",
                        "desc": "Tim Hardaway Jr. misses a jump shot from 19 feet out.",
                        "playerFname": "Tim",
                        "playerLname": "Hardaway Jr.",
                        "eventId": "4",
                        "eventDesc": "Field Goal Missed",
                        "distance": "19",
                        "xCoord": "1.3",
                        "yCoord": "19",
                        "teamId": "75"
                    },
                    {
                        "clk": "4:08",
                        "id": "99",
                        "ptsH": "21",
                        "ptsV": "31",
                        "tm": "V",
                        "desc": "Jon Horford with an offensive rebound.",
                        "playerFname": "Jon",
                        "playerLname": "Horford",
                        "eventId": "5",
                        "eventDesc": "Offensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "3:54",
                        "id": "100",
                        "ptsH": "21",
                        "ptsV": "33",
                        "tm": "V",
                        "desc": "Spike Albrecht makes a layup shot.",
                        "playerFname": "Spike",
                        "playerLname": "Albrecht",
                        "eventId": "3",
                        "eventDesc": "Field Goal Made",
                        "distance": "0",
                        "xCoord": "0",
                        "yCoord": "0",
                        "teamId": "75"
                    },
                    {
                        "clk": "3:51",
                        "id": "101",
                        "ptsH": "21",
                        "ptsV": "33",
                        "tm": "H",
                        "desc": "Lou take a 20-second timeout.",
                        "playerFname": "",
                        "playerLname": "",
                        "eventId": "11",
                        "eventDesc": "Timeout",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "3:33",
                        "id": "102",
                        "ptsH": "21",
                        "ptsV": "33",
                        "tm": "V",
                        "desc": "Shooting foul committed by Nik Stauskas.",
                        "playerFname": "Nik",
                        "playerLname": "Stauskas",
                        "eventId": "8",
                        "eventDesc": "Foul",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "3:33",
                        "id": "103",
                        "ptsH": "21",
                        "ptsV": "33",
                        "tm": "H",
                        "desc": "Official TV timeout.",
                        "playerFname": "",
                        "playerLname": "",
                        "eventId": "11",
                        "eventDesc": "Timeout",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "3:33",
                        "id": "104",
                        "ptsH": "22",
                        "ptsV": "33",
                        "tm": "H",
                        "desc": "Luke Hancock makes free throw 1 of 2.",
                        "playerFname": "Luke",
                        "playerLname": "Hancock",
                        "eventId": "1",
                        "eventDesc": "Free Throw Made",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "3:33",
                        "id": "105",
                        "ptsH": "23",
                        "ptsV": "33",
                        "tm": "H",
                        "desc": "Luke Hancock makes free throw 2 of 2.",
                        "playerFname": "Luke",
                        "playerLname": "Hancock",
                        "eventId": "1",
                        "eventDesc": "Free Throw Made",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "3:22",
                        "id": "106",
                        "ptsH": "23",
                        "ptsV": "35",
                        "tm": "V",
                        "desc": "Tim Hardaway Jr. makes a layup shot.",
                        "playerFname": "Tim",
                        "playerLname": "Hardaway Jr.",
                        "eventId": "3",
                        "eventDesc": "Field Goal Made",
                        "distance": "0",
                        "xCoord": "0",
                        "yCoord": "0",
                        "teamId": "75"
                    },
                    {
                        "clk": "3:02",
                        "id": "107",
                        "ptsH": "23",
                        "ptsV": "35",
                        "tm": "H",
                        "desc": "Peyton Siva misses a layup shot.",
                        "playerFname": "Peyton",
                        "playerLname": "Siva",
                        "eventId": "4",
                        "eventDesc": "Field Goal Missed",
                        "distance": "0",
                        "xCoord": "0",
                        "yCoord": "0",
                        "teamId": "120"
                    },
                    {
                        "clk": "3:02",
                        "id": "108",
                        "ptsH": "23",
                        "ptsV": "35",
                        "tm": "H",
                        "desc": "Gorgui Dieng with an offensive rebound.",
                        "playerFname": "Gorgui",
                        "playerLname": "Dieng",
                        "eventId": "5",
                        "eventDesc": "Offensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "3:02",
                        "id": "109",
                        "ptsH": "23",
                        "ptsV": "35",
                        "tm": "H",
                        "desc": "Lou take a 20-second timeout.",
                        "playerFname": "",
                        "playerLname": "",
                        "eventId": "11",
                        "eventDesc": "Timeout",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "2:57",
                        "id": "110",
                        "ptsH": "26",
                        "ptsV": "35",
                        "tm": "H",
                        "desc": "Luke Hancock makes a 3-point jump shot from 24 feet out. Gorgui Dieng with the assist.",
                        "playerFname": "Luke",
                        "playerLname": "Hancock",
                        "eventId": "3",
                        "eventDesc": "Field Goal Made",
                        "distance": "24",
                        "xCoord": "18.3",
                        "yCoord": "15.4",
                        "teamId": "120"
                    },
                    {
                        "clk": "2:47",
                        "id": "111",
                        "ptsH": "26",
                        "ptsV": "35",
                        "tm": "H",
                        "desc": "Personal foul committed by Luke Hancock.",
                        "playerFname": "Luke",
                        "playerLname": "Hancock",
                        "eventId": "8",
                        "eventDesc": "Foul",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "2:47",
                        "id": "112",
                        "ptsH": "26",
                        "ptsV": "36",
                        "tm": "V",
                        "desc": "Glenn Robinson III makes free throw 1 of 2.",
                        "playerFname": "Glenn",
                        "playerLname": "Robinson III",
                        "eventId": "1",
                        "eventDesc": "Free Throw Made",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "2:47",
                        "id": "113",
                        "ptsH": "26",
                        "ptsV": "36",
                        "tm": "V",
                        "desc": "Glenn Robinson III misses free throw 2 of 2.",
                        "playerFname": "Glenn",
                        "playerLname": "Robinson III",
                        "eventId": "2",
                        "eventDesc": "Free Throw Missed",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "75"
                    },
                    {
                        "clk": "2:47",
                        "id": "114",
                        "ptsH": "26",
                        "ptsV": "36",
                        "tm": "H",
                        "desc": "Gorgui Dieng with a defensive rebound.",
                        "playerFname": "Gorgui",
                        "playerLname": "Dieng",
                        "eventId": "6",
                        "eventDesc": "Defensive Rebound",
                        "distance": "",
                        "xCoord": "",
                        "yCoord": "",
                        "teamId": "120"
                    },
                    {
                        "clk": "2:36",
                        "id": "115",
                        "ptsH": "29",
                        "ptsV": "36",
                        "tm": "H",
                        "desc": "Luke Hancock makes a 3-point jump shot from 24 feet out. Gorgui Dieng with the assist.",
                        "playerFname": "Luke",
                        "playerLname": "Hancock",
                        "eventId": "3",
                        "eventDesc": "Field Goal Made",
                        "distance": "24",
                        "xCoord": "14",
                        "yCoord": "19.5",
                        "teamId": "120"
                    }
                ]
            }
        ]
    }
}